from decimal import Decimal

ENV_DEV = "dev"
ENV_UAT = "uat"
ENV_STAGING = "staging"
ENV_PROD = "prod"
ENV_CHOICES = (ENV_DEV, ENV_UAT, ENV_STAGING, ENV_PROD)

ROLE_SUPER_ADMIN = "SUPER_ADMIN"
ROLE_OPS = "OPS"
ROLE_SUPPORT = "SUPPORT"
ROLE_AUDITOR = "AUDITOR"
ADMIN_ROLES = (ROLE_SUPER_ADMIN, ROLE_OPS, ROLE_SUPPORT, ROLE_AUDITOR)

TX_PENDING = "PENDING"
TX_SUCCESS = "SUCCESS"
TX_FAILED = "FAILED"
TX_REVERSED = "REVERSED"
TX_STATUS_CHOICES = (TX_PENDING, TX_SUCCESS, TX_FAILED, TX_REVERSED)

KYC_PENDING = "pending"
KYC_VERIFIED = "verified"
KYC_REJECTED = "rejected"

NGN_TRANSFER_FEE = Decimal("10.50")
KYC_LIMIT_AMOUNT = Decimal("20000.00")
